# Site settings
title: Anderson Menezes desenvolvedor front-end.
email: andersomxp@gmail.com
description: Apaixonado por projetos open source gosto de compartilhar conhecimentos e aprender algo novo sempre.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andersonweb.github.io" # the base hostname & protocol for your site
twitter_username: amenezesw
# Build settings
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null
sass:
  style: compressed
